2021-05-04 21:49:30,658 ERROR: Exception on /explore [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aaron/dev/grovr/app/routes.py", line 136, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2021-05-04 21:49:37,207 INFO: Grovr startup [in /Users/aaron/dev/grovr/app/__init__.py:34]
