2021-05-04 21:49:30,658 ERROR: Exception on /explore [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aaron/dev/grovr/app/routes.py", line 136, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2021-05-04 21:49:37,207 INFO: Grovr startup [in /Users/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 11:13:37,770 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 14:57:27,783 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 15:00:15,617 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:05:13,598 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:05:13,654 ERROR: Exception on /index [GET] [in /home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/aaron/dev/grovr/app/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2021-05-05 16:05:23,656 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:05:27,616 ERROR: Exception on /explore [GET] [in /home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/aaron/dev/grovr/app/routes.py", line 138, in explore
    page = request.get.args('page', 1, type=int)
  File "/home/aaron/dev/grovr/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'get'
2021-05-05 16:05:48,458 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:17:43,343 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:18:40,375 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:20:36,602 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
2021-05-05 16:24:59,625 INFO: Grovr startup [in /home/aaron/dev/grovr/app/__init__.py:34]
